#!/bin/sh

# Shell script to handle installs on BSD-systems.
# Copyright (C) 2001-2004 Open Challenge B.V.
# Copyright (C) 2004-2005 OpenEyeT Professional Services.
# Copyright (C) 2005-2018 QNH.
# Copyright (C) 2019 Siem Korteweg.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.
# If not, write to the Free Software Foundation,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
#
# Contact information: https://sourceforge.net/projects/sysconfcollect/support

# SCC-release: 1.19.44
# ID:          $Id: BSDinstall 6217 2019-03-22 18:46:12Z siemkorteweg $

if [ $2 = "POST-INSTALL" ]
then
	# Empty directories are not installed on *BSD.
	while read dir perm
	do
		mkdir -p "${dir}"
		chmod "${perm}" "${dir}"
	done <<-_EOF_
		/var/opt/scc-srv/conf				770
		/var/opt/scc-srv/data/log			755
		/var/opt/scc-srv/data/transfer			771
		/var/opt/scc-srv/data/transfer/mail		770
		/var/opt/scc-srv/data/transfer/cp		771
		/var/opt/scc-srv/tmp				770
	_EOF_

	# The new release has been installed. Customize some settings recorded from the previous version.
	/opt/scc-srv/bin/scc-update --postinstall
fi

if [ $2 = "POST-DEINSTALL" ]
then
	rmdir /opt/scc-srv 2>/dev/null
fi

# We do not need pre-install code. Possible preparations have been done by the DEINSTALL.

exit 0
