#!/bin/sh

# Shell script to handle installs on archlinux with pacman.
# Copyright (C) 2007-2018 QNH.
# Copyright (C) 2019 Siem Korteweg.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.
# If not, write to the Free Software Foundation,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
#
# Contact information: https://sourceforge.net/projects/sysconfcollect/support

# SCC-release: 1.19.44
# ID:          $Id: pacman-install 6217 2019-03-22 18:46:12Z siemkorteweg $

# Retrieve configuration of previous version and generate summaries with the new software.
post_install() {
	/opt/scc-srv/bin/scc-update --postinstall
	return
}

post_upgrade() {
	post_install
	return
}

case "${1}" in
post_install)
	post_install
	;;

post_upgrade)
	post_install
	;;
esac

exit 0
