#!/bin/sh

# Generate Debian package to install scc-srv by means of dpkg.
# Copyright (C) 2001-2004 Open Challenge B.V.
# Copyright (C) 2004-2005 OpenEyeT Professional Services.
# Copyright (C) 2005-2018 QNH.
# Copyright (C) 2019 Siem Korteweg.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.
# If not, write to the Free Software Foundation,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
#
# Contact information: https://sourceforge.net/projects/sysconfcollect/support

# SCC-release: 1.19.44
# ID:          $Id: debian-gen-scc-srv 6217 2019-03-22 18:46:12Z siemkorteweg $

# This program requires to be called in a directory with the following hierarchy:
#
#	install				pre/post install scripts
#	software/opt/scc-srv		bin, doc and man
#	software/var/opt/scc-srv	conf, data and newconfig
#
# It uses the following programs:
#
#	ar
#	gzip
#
# After using this program, the directory contains one file:
#
#	scc-srv_1.19.44_all.deb
#
# Provide an alternative version as first argument.
# Be aware of the limitations in the format of the version.

TESTING="testing"
x="$(echo "${TESTING}" 2>/dev/null)"
if [ "${x}" != "${TESTING}" ]
then
	exec /bin/ksh ${0} "$@"

	echo "${0}: cannot find ksh" >&2
	exit 2
fi

ProgName=${0##*/};			export ProgName

if [ ! -x /usr/bin/ar ]
then
	echo "${ProgName}: missing /usr/bin/ar (part of binutils), cannot package software" >&2
	exit 2
fi

VERSION=${1:-1.19.44}

version=${VERSION}
patch="1"

if [ -d /usr/xpg4/bin ]
then
	PATH="/usr/xpg4/bin:${PATH}"
fi

my_md5()
{
	exe="$(which md5sum 2>/dev/null)"
	if [ -x "${exe}" ]
	then
		"${exe}" "${1}" | awk '{ print $1 }'
	else
		exe="$(which md5 2>/dev/null)"
		if [ -x "${exe}" ]
		then
			"${exe}" "${1}" | awk '{ print $4 }'
		fi
	fi
}

for f in *
do
	if [ -f "${f}" ]
	then
		echo "${f}"
	fi
done >file_list

( cd software; tar cf ../data.tar . )
gzip data.tar

echo "2.0" >debian-binary

(
	cd software
	find . -type f		|
	sed -e "s@^\./@@"	|
	while read file
	do
		echo "$(my_md5 ${file})  ${file}"
	done
) >md5sums

cp install/postinstall postinst
cp install/preremove prerm

cat >control <<_EOF_
Package: scc-srv
Version: ${version}-${patch}
Section: admin
Priority: extra
Architecture: all
Depends: sharutils
Installed-Size: 656
Maintainer: siemkorteweg@users.sourceforge.net
Description: System Configuration Collector Server
_EOF_

rm -f control.tar control.tar.gz
tar cf control.tar md5sums control postinst prerm
gzip control.tar
rm -f md5sums control postinst prerm

pkg_file=scc-srv_${version}-${patch}_all.deb
echo "!<arch>" >${pkg_file}			# Specific magic number.
ar -q ${pkg_file} debian-binary			# Add the files
ar -q ${pkg_file} control.tar.gz		# in this
ar -q ${pkg_file} data.tar.gz			# order!

rm -rf install software $(cat file_list) debian-binary control.tar.gz data.tar.gz

exit 0
