#!/bin/sh

# Production of scc-srv for OpenBSD.
# Copyright (C) 2001-2004 Open Challenge B.V.
# Copyright (C) 2004-2005 OpenEyeT Professional Services.
# Copyright (C) 2005-2018 QNH.
# Copyright (C) 2019 Siem Korteweg.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.
# If not, write to the Free Software Foundation,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
#
# Contact information: https://sourceforge.net/projects/sysconfcollect/support

# SCC-release: 1.19.44
# ID:          $Id: openbsd-gen-scc-srv 6217 2019-03-22 18:46:12Z siemkorteweg $

# This program requires to be called in a directory with the following hierarchy:
#
#	install				pre/post install scripts
#	software/opt/scc-srv		bin, doc and man
#	software/var/opt/scc-srv	conf, data and newconfig
#
# Program relocate is used to change this default hierarchy into OpenBSD practices:
#
#	install					post install scripts
#	software/usr/local			bin, doc and man
#	software/usr/local/share/scc-srv	conf, data and newconfig
#
# After using this program, the directory contains one file:
#
#	scc-srv-1.19.44-OpenBSD.tgz
#
# Provide an alternative version as first argument.
# Be aware of the limitations in the format of the version.

TESTING="testing"
x="$(echo "${TESTING}" 2>/dev/null)"
if [ "${x}" != "${TESTING}" ]
then
	exec /bin/ksh ${0} "$@"

	echo "${0}: cannot find ksh" >&2
	exit 2
fi

ProgName=${0##*/};			export ProgName

tar --format=ustar -z -cf ./dummy.tgz /dev/null 2>/dev/null
if [ $? -ne 0 ]
then
	echo "${ProgName}: cannot find gnu tar" >&2
	rm -f dummy.tgz
	exit 2
fi
rm -f dummy.tgz

VERSION=${1:-1.19.44}

my_sha()
{
	exe="$(which sha256sum 2>/dev/null)"
	if [ -x "${exe}" ]
	then
		"${exe}" "${1}" | awk '{ print $1 }'
	else
		exe="$(which sha256 2>/dev/null)"
		if [ -x "${exe}" ]
		then
			"${exe}" "${1}" | awk '{ print $4 }'
		fi
	fi
}

./relocate --data /usr/local/share/scc-srv --sw /usr/local --ign ${ProgName}

# Record all files to remove them at the end.
for f in *
do
	if [ -f "${f}" ]
	then
		echo "${f}"
	fi
done >remove_list
echo remove_list >>remove_list

PKG=scc-srv-${VERSION}.OpenBSD.tgz

# Correct for the cwd /usr/local prefix.
mv software/usr/local/* .

# Use separate sub directory to avoid conflicts with scc concerning CHANGELOG and COPYRIGHT files.
mkdir -p share/doc/scc-srv
mv doc/* share/doc/scc-srv/ >/dev/null 2>/dev/null

echo "System Configuration Collector Server ${VERSION}" >+COMMENT
{
	echo "scc server offers a web-interface for the scc data that is sent to the server."
	echo ""
	echo "Homepage:"
	echo "https://sourceforge.net/projects/sysconfcollect"
} >+DESC

LIST="+CONTENTS"
PKG_FILES="+CONTENTS +COMMENT +DESC"

cat >${LIST} <<-_X_
	@name scc-srv-${VERSION}.OpenBSD
	@arch *
	@owner root
	@group wheel
	+DESC
	@sha $(my_sha ./+DESC)
	@size $(ls -l ./+DESC | awk '{ print $5 }')
	@cwd /usr/local
	@unexec-delete echo "/usr/local/bin/scc-update --preremove"
	@unexec-delete /usr/local/bin/scc-update --preremove
_X_

# We should not tar directories, so we collect the names of files in a file for use with tar.
>file_list
for f in $(find bin -type f; find man -type f; find share -type f)
do
	echo ${f}
	echo "@sha $(my_sha ${f})"
	echo "@size $(ls -l ${f} | awk '{ print $5 }')"

	echo ${f} >>file_list
done >>${LIST}

cat >>${LIST} <<-_X_
	@exec /usr/local/bin/scc-update --postinstall
_X_

tar --format=ustar -z -cf ${PKG} ${PKG_FILES} $(cat file_list)
chmod 444 ${PKG}

rm -rf bin doc man conf data newconfig software share $(cat file_list) file_list $(cat remove_list) +* install

exit 0
