#!/bin/sh

# Generate Slackware package to install scc-srv by means of installpkg.
# Copyright (C) 2006-2018 QNH.
# Copyright (C) 2019 Siem Korteweg.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.
# If not, write to the Free Software Foundation,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
#
# Contact information: https://sourceforge.net/projects/sysconfcollect/support

# SCC-release: 1.19.44
# ID:          $Id: slackware-gen-scc-srv 6217 2019-03-22 18:46:12Z siemkorteweg $

# This program requires to be called in a directory with the following hierarchy:
#
#	install				pre/post install scripts
#	software/opt/scc		bin, doc and man
#	software/var/opt/scc-srv	conf, data and newconfig
#
# It uses the following programs:
#
#	ar
#	gzip
#
# After using this program, the directory contains one file:
#
#	scc-1.19.44-noarch-1.tgz
#
# Provide an alternative version as first argument.
# Be aware of the limitations in the format of the version.

TESTING="testing"
x="$(echo "${TESTING}" 2>/dev/null)"
if [ "${x}" != "${TESTING}" ]
then
	exec /bin/ksh ${0} "$@"

	echo "${0}: cannot find ksh" >&2
	exit 2
fi

ProgName=${0##*/};			export ProgName

uid=$(id | sed -e 's/(.*//' -e 's/.*=//')
if [ "${uid}" != "0" ]
then
	echo "${ProgName}: only root should run this program" >&2
	exit 2
fi

VERSION=${1:-1.19.44}

for f in *
do
	if [ -f "${f}" ]
	then
		echo "${f}"
	fi
done >file_list

mkdir -p software/install
cat >software/install/doinst.sh <<_X_
#!/bin/sh
exec /opt/scc-srv/bin/scc-update --postinstall
_X_
chmod 500 software/install/doinst.sh

{
	# 11 lines for proper formatting.
	echo "scc-srv: System Configuration Collector Server"
	echo "scc-srv:"
	echo "scc-srv: Offers a web-interface for the scc data that is sent to the server."
	echo "scc-srv:"
	echo "scc-srv: Homepage: https://sourceforge.net/projects/sysconfcollect"
	echo "scc-srv:"
	echo "scc-srv:"
	echo "scc-srv:"
	echo "scc-srv:"
	echo "scc-srv:"
	echo "scc-srv:"
} >software/install/slack-desc

cd software
# Slackware installpkg forces the ownership and permissions from our
# directories and files upon the directories and files that are already
# present on the system. Avoid that directories like /opt and /var/opt
# are not accessible for ordinary users.
chown -R root:root .
chmod 755 opt
find var -type d | xargs chmod 755			# Default for data.
chmod 770 var/opt/scc-srv/conf
chmod 771 var/opt/scc-srv/data/transfer
chmod 770 var/opt/scc-srv/data/transfer/mail
chmod 711 var/opt/scc-srv/data/transfer/cp

# The installpkg command checks for a single entry starting with './'.
# First add only the current directory and then add the subdirectories.
tar cf ../scc-srv.tar --no-recursion .
mv ../scc-srv.tar .
tar rf ./scc-srv.tar install opt/scc-srv var/opt/scc-srv
gzip -9c <./scc-srv.tar >../scc-srv-${VERSION}-noarch-1.tgz
cd ..

rm -rf software  install $(cat file_list)

exit 0
