#!/bin/sh

# Production of scc-srv for slitaz.
# Copyright (C) 2009-2018 QNH.
# Copyright (C) 2019 Siem Korteweg.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.
# If not, write to the Free Software Foundation,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
#
# Contact information: https://sourceforge.net/projects/sysconfcollect/support

# SCC-release: 1.19.44
# ID:          $Id: slitaz-gen-scc-srv 6217 2019-03-22 18:46:12Z siemkorteweg $

# This program requires to be called in a directory with the following hierarchy:
#
#	install				pre/post install scripts
#	software/opt/scc-srv		bin, doc and man
#	software/var/opt/scc-srv	conf, data and newconfig
#
# After using this program, the directory contains one file:
#
#	scc-srv-1.19.44.tazpkg
#
# Provide an alternative version as first argument.
# Be aware of the limitations in the format of the version.

my_md5()
{
	exe="$(which md5sum 2>/dev/null)"
	if [ -x "${exe}" ]
	then
		"${exe}" "${1}" | awk '{ print $1 }'
	else
		exe="$(which md5 2>/dev/null)"
		if [ -x "${exe}" ]
		then
			"${exe}" "${1}" | awk '{ print $4 }'
		fi
	fi
}

VERSION=${1:-1.19.44}

for f in *
do
	if [ -f "${f}" ]
	then
		echo "${f}"
	fi
done >file_list

mv software fs

# Slitaz does not provice man, get rid of the manual pages.
rm -rf fs/opt/scc-srv/man

find fs					|
sort					|
cpio -c -o >fs.cpio 2>/dev/null
UNPACKED_SIZE="$(ls -l fs.cpio | awk '{ printf( "%d\n", $5 / 1024 ) }')"
gzip fs.cpio
PACKED_SIZE="$(ls -l fs.cpio.gz | awk '{ printf( "%d\n", $5 / 1024 ) }')"

cat >receipt <<_X_
# SliTaz package receipt.

PACKED_SIZE="${PACKED_SIZE}K"
UNPACKED_SIZE="${UNPACKED_SIZE}K"
PACKAGE="scc-srv"
VERSION="${VERSION}"
CATEGORY="utilities"
SHORT_DESC="System Configuration Collector Server"
MAINTAINER="siemkorteweg@users.sourceforge.net"
WEB_SITE="https://sourceforge.net/projects/sysconfcollect"
WGET_URL="https://sourceforge.net/projects/sysconfcollect/files/scc-srv/scc-srv-${VERSION}.src.tar.gz"

_X_

# Avoid that the variables in the postin are substituted by the here-document construct.
cat >>receipt << "_X_"
post_install()
{
	/opt/scc-srv/bin/scc-update --postinstall
}
_X_

find fs -type f			|
sort				|
while read file
do
	echo "$(my_md5 ${file}) ${file}"		|
	sed -e 's/ fs/ /'
done >md5sum

find fs -type f			|
sort				|
sed -e 's@^fs@@' >files.list

{
	echo "fs.cpio.gz"
	echo "receipt"
	echo "files.list"
	echo "md5sum"
}	|
cpio -c -o >scc-srv-${VERSION}.tazpkg 2>/dev/null

rm -rf fs install $(cat file_list) fs.cpio fs.cpio.gz receipt files.list md5sum

exit 0
