.TH scc-wrapper.cgi 1 "SCC-SRV" 
.nf


.SH  NAME
.nf

	scc-wrapper.cgi - wrapper for cgi-handling in SCC

.SH  RELEASE
.nf

	scc-srv	1.19.44

.SH  SYNOPSIS
.nf

	scc-wrapper.cgi

.SH  DESCRIPTION
.nf

	Wrapper to call scc.cgi with the proper argument. The current 
	directory is used to determine the realm for scc.cgi.

.SH  OPTIONS
.nf

	None.

.SH  ARGUMENTS
.nf

	None.

.SH  DIAGNOSTICS
.nf

	This program does not produce any diagnostics.

.SH  EXTERNAL INFLUENCES
.nf

	This program executes /opt/scc-srv/bin/scc.cgi

.SH  COPYRIGHT
.nf

	scc-wrapper.cgi is free software under the terms of the GNU General Public 
	License. Copyright (C) 2001-2004 Open Challenge B.V.,
	2004-2005 OpenEyeT Professional Services, 2005-2018 QNH, 2019 Siem Korteweg.

.SH  SEE ALSO
.nf

	scc-baseline(1), scc-changes(1), scc-debug(1), scc-pull(1), scc-realm(1),
	scc-receive-mail(1), scc-rules(1), scc-setup(1), scc-smt(1), scc-summary(1),
	scc-syscmp(1), scc-transfer(1), scc-update(1), scc-wrapper.cgi(1), scc.cgi(1),
	scc-srv(5)

.SH  VERSION
.nf

	$Revision: 6217 $

